####
#### the description is used in the feed.xml file
####

description: "ParaMonte is a serial/parallel library of Monte Carlo routines for sampling mathematical density functions of arbitrary dimensions and Machine Learning (ML) algorithms for scientific inference."

showSolution:       false
overrideLocal:      true

####
#### social media links.
####

lab:
  facebook:         cdslab
  medium:           cdslab
  github:           cdslaborg
  twitter:          cdslaborg
  instagram:        cdslaborg

####
#### this property is useful for conditional filtering of content that is separate from the PDF.
####

output: web

####
#### this appears on the top navigation bar next to the home button
####

topnav_title: "ParaMonte 2"

####
#### this appears in the html browser tab for the site title (seen mostly by search engines, not users)
####

site_title: "ParaMonte: Parallel Monte Carlo and Machine Learning Library"

####
#### this appears in the footer
####

company_name: Computational Data Science Lab

####
#### if you're using GitLab, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.
####

github_editme_path: cdslaborg/paramonted/tree/main/generic/2/
#gitlab_editme_path: https://github.com/cdslaborg/paramonted/tree/main/generic/2

####
#### if you're using disqus for comments, add the shortname here. if not, leave this value blank.
####

disqus_shortname: paramonte

####
#### if you have google-analytics ID, put it in. if not, edit this value to blank.
####

google_analytics:

####
#### sitemap.xml file only.
####

companyurl: https://www.cdslab.org
url:        https://www.cdslab.org/paramonte/2
baseurl:

####
#### ParaMonte Version Majors.
####

pmvmpython: 3
pmvmmatlab: 3
pmvmfortran: 2
pmvmcpp: 2
pmvmc: 2
pmvm: 2

####
#### compiler / dependency-library versions.
####

msvcVersionWindows: 2019

libgfortranLinux: libgfortran.so.5
gnuVersionMinimum: 10.3.0
gnuVersionMajorWindows: 13
gnuVersionMajorDarwin: 13
gnuVersionMajorLinux: 13
gnuVersionWindows: 13.1.0
gnuVersionDarwin: 13.1.0
gnuVersionLinux: 13.1.0
gnuVersionYear: 2023

intelVersionMajorWindows: 2021
intelVersionMajorDarwin: 2021
intelVersionMajorLinux: 2021
intelVersionWindows: 2021.8.0
intelVersionDarwin: 2021.8.0
intelVersionLinux: 2021.8.0
intelVersionYear: 2023

openmpiVersionDarwin: 5.0.5
openmpiVersionLinux: 4.1.2

mpichVersionDarwin: 4.2.3
mpichVersionLinux: 4.0

cafVersionDarwin: 2.9.0
cafVersionLinux: 2.9.0
cafVersionYear: 2020

cmakeVersion: 3.21.0

####
#### GitHub Links:
####

codecov: "https://www.cdslab.org/paramonte/codecov"
githubTree: "https://github.com/cdslaborg/paramonte/tree/main"
githubIssues: "https://github.com/cdslaborg/paramonte/issues"
githubArchive: "https://github.com/cdslaborg/paramonte/archive"
githubReleases: "https://github.com/cdslaborg/paramonte/releases"
githubReleasesAuxil: "https://github.com/cdslaborg/paramonte/releases/auxil"
githubReleaseCurrent: "https://github.com/cdslaborg/paramonte/releases/2024.04.29"
githubReleaseCurrentDownload: "https://github.com/cdslaborg/paramonte/releases/download/2024.04.29"

####
#### the preview server used. Leave as is.
####

host: 127.0.0.1

####
#### the port where the preview is rendered. You can leave this as is unless you have other Jekyll
#### builds using this same port that might cause conflicts. in that case, use another port such as 4006.
####

port: 4000

####
#### these are the files and directories that jekyll will exclude from the build.
####

exclude:
  - .idea/
  - .gitignore
  - vendor

####
#### disable/enable Feedback line.
####

feedback_disable: false
feedback_subject_line: ParaMonte Library

####
#### if you uncomment the line below, it changes the Feedback text.
####

feedback_text: "Contact"

####
#### used as a contact email for the Feedback link in the top navigation bar.
####

feedback_email: shahmoradi@utexas.edu
feedback_link: shahmoradi@utexas.edu

####
#### library used for syntax highlighting.
####

highlighter: rouge

####
#### filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
####

rouge:
    syntax_highlighter_opts

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 syntax_highlighter_opts:
   default_lang: nil

####
#### collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true
####

collections:
  tooltips:
    output: false

####
#### these are defaults used for the frontmatter for these file types
####

defaults:
  -
    scope:
      path:     ""
      type:     "pages"
    values:
      layout:   "page"
      comments: true
      search:   true
      sidebar:  home_sidebar
      topnav:   topnav
  -
    scope:
      path:     ""
      type:     "tooltips"
    values:
      layout:   "page"
      comments: true
      search:   true
      tooltip:  true

  -
    scope:
      path:     ""
      type:     "posts"
    values:
      layout:   "post"
      comments: true
      search:   true
      sidebar:  home_sidebar
      topnav:   topnav

sidebars:
- home_sidebar

#plugins: ['jekyll-lunr-js-search']

#github: [metadata]

#ref: tomjoht/documentation-theme-jekyll