source "https://rubygems.org"

gem 'wdm', '>= 0.1.0' if Gem.win_platform?

# to publish on github page
#gem 'github-pages', group: :jekyll_plugins

# to publich without github page
gem 'jekyll'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'
gem 'jemoji'
gem 'jekyll-readme-index'

