destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/notes-pdf"
port: 4010
output: pdf
product: notes
print_title: Jekyll theme for documentation — notes product
print_subtitle: version 6.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: home_sidebar
